# Generated by Django 4.1.7 on 2023-03-02 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descrição',
            new_name='descricao',
        ),
    ]
