# Generated by Django 4.1.7 on 2023-03-10 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_produto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Padaria'), (2, 'Açougue'), (3, 'Mercearia'), (4, 'Congelados e frios'), (5, 'Hortifruti'), (6, 'Produtos de Limpeza'), (7, 'Higiene Pessoal'), (8, 'Bebidas'), (9, 'Papelaria')], default=2),
        ),
    ]
