# Generated by Django 4.1.7 on 2023-03-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0007_alter_produto_descricao_alter_produto_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='simple_name',
            field=models.CharField(default='', editable=False, max_length=50),
        ),
    ]
