# Generated by Django 4.1.7 on 2023-05-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('cod', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[(1, 'entrada'), (0, 'saída')], max_length=20)),
                ('usuario', models.CharField(max_length=50)),
                ('data', models.DateField()),
            ],
        ),
    ]
