# Generated by Django 4.1.7 on 2023-05-20 22:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0002_alter_chamado_cod_alter_chamado_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chamado',
            name='tipo',
        ),
        migrations.AddField(
            model_name='chamado',
            name='tipoChamado',
            field=models.IntegerField(choices=[(1, 'entrada'), (0, 'saída')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chamado',
            name='data',
            field=models.DateField(default=datetime.date(2023, 5, 20)),
        ),
    ]
