# Generated by Django 4.1.7 on 2023-05-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chamado', '0003_remove_chamado_tipo_chamado_tipochamado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chamado',
            name='titulo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chamado',
            name='tipoChamado',
            field=models.IntegerField(choices=[(1, 'Entrada de Produtos'), (0, 'Saída de Produtos')]),
        ),
    ]
